M48
; DRILL file {KiCad 7.0.9} date Wed Nov 29 15:21:26 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-29T15:21:26-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X3.9439Y-3.2199
X3.9439Y-5.0683
X4.9089Y-3.2199
X4.9089Y-5.0683
T0
M30
